CREATE TABLE IF NOT EXISTS training_config (
training_id TEXT PRIMARY KEY,
benchmark TEXT DEFAULT 'sysbench',
cluster_name TEXT,
host TEXT,
port TEXT,
db TEXT,
user TEXT,
password TEXT,
os_user   TEXT,
chroot    TEXT,
init_param  TEXT,
workload_restore TEXT,
dist_dn_port  TEXT,
distributed TEXT,
omm_password TEXT,
opengauss_node_path TEXT,
root_password TEXT,
has_pressure_tab INTEGER DEFAULT 0,
tables TEXT DEFAULT '20',
table_size TEXT DEFAULT '8000000',
mode TEXT DEFAULT 'oltp_read_write',
sampling_number TEXT DEFAULT '10',
iteration TEXT DEFAULT '2',
threads TEXT DEFAULT '10',
running_time TEXT,
ranked_knobs_number TEXT DEFAULT '10',
online TEXT DEFAULT 'False',
finetune TEXT DEFAULT 'True',
restart_when_finetune TEXT DEFAULT 'False',
time_wait TEXT DEFAULT '30',
warm_up_time TEXT DEFAULT '10',
schema_name TEXT DEFAULT 'public',
remote_cache_path TEXT,
local_cache_path TEXT,
use_local TEXT,
sql_num TEXT,
read_write_ratio TEXT,
json_extract_result_path TEXT,
workload TEXT,
sql_num_print TEXT DEFAULT '500',
memory TEXT DEFAULT '64',
start_time TEXT,
end_time TEXT,
is_custom_payloads TEXT,
table_domain_distribution TEXT,
query_comparison_operator_ratio TEXT,
query_logic_predicate_num TEXT,
average_aggregation_operator_num TEXT,
average_query_column_num TEXT,
group_by_ratio_if_read_sql TEXT,
order_by_desc_or_asc_if_grouped TEXT,
average_table_num TEXT,
process INTEGER DEFAULT 0,
status TEXT DEFAULT '0',
log_path TEXT,
file_name TEXT
);

CREATE TABLE IF NOT EXISTS parameter_recommendation (
parameter_id TEXT PRIMARY KEY,
training_id TEXT,
cluster_name TEXT,
db TEXT,
start_time TEXT,
initial_tps TEXT,
optimal_tps TEXT,
initial_parameter_values TEXT,
advise_parameter_values TEXT,
performance_improvement TEXT
);

CREATE TABLE IF NOT EXISTS training_progress (
progress_id INTEGER PRIMARY KEY AUTOINCREMENT,
training_id TEXT,
tuning_round TEXT,
parameter_type TEXT,
running_time TEXT,
training_parameter TEXT,
tps TEXT
);

CREATE TABLE IF NOT EXISTS tuning_log (
training_id TEXT,
log_id TEXT PRIMARY KEY,
cluster_name TEXT,
start_time TEXT,
tuning_start_time TEXT,
db_start_time TEXT,
pressure_start_time TEXT,
db_size TEXT,
pressure_size TEXT,
tuning_size TEXT,
db_path TEXT,
pressure_path TEXT,
tuning_path TEXT
);
