version: 7.0.0
server:
  proxy:
    hostname: localhost
    port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  ssl:
    enabled: false
    client-auth: none
    key-alias: opengauss
    key-store: ssl/keystore.p12
    key-store-password: '******'
    key-store-type: PKCS12
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: >
      TLS_AES_256_GCM_SHA384,
      TLS_AES_128_GCM_SHA256,
      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
      TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
spring:
  profiles:
    active: prod
  messages:
    basename: i18n/messages
  servlet:
     multipart:
       max-file-size:  20GB
       max-request-size:  20GB
  mvc:
    async:
      request-timeout: 60000
  sql:
    init:
      mode: always
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      cache:
        period: 3600  # 缓存静态资源
      chain:
        compressed: true
      static-locations: classpath:/static/
mybatis-plus:
  typeAliasesPackage: org.opengauss.admin.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: postgresql
  supportMethodsArguments: true
  params: count=countSql 

plugin:
  mainPackage: org.opengauss.admin
  runMode: prod
  #  runMode: deployment
  pluginPath:
    - ~/visualtool-plugin
monitor:
  handle:
    enabled: true
    report-dir: ./logs/handle
#  pluginRestPathPrefix: /static-plugin
agent:
  localPath:  ./agent
  agentName: datakit-agent-${version}-runner.jar
disruptor:
  bufferSize: 1024
  backpressure:
    threshold: 10
    initDelay: 1
    maxDelay: 100
    factor: 2
management:
  server:
    port: ${server.port}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'prometheus'
      base-path: "/"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    enable:
      jvm: false
      logback: false
      files: false
      tomcat: false
      executor: false
      disk: false
      uptime: false
      integration: false
