system:
  defaultStoragePath: /Users/xielibo/uploadPath/gausstool
  whitelist:
    enabled: false
server:
  port: 9494
  servlet:
    context-path: /
logging:
  file:
    path: /visualtool-api/logs/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # For openGauss
    #driver-class-name: org.opengauss.Driver
    #url: jdbc:opengauss://127.0.0.1:5432/databasename?currentSchema=public&batchMode=off
    #username: username
    #password: password
    # For Intarkdb
    driver-class-name: org.intarkdb.Driver
    url: jdbc:intarkdb:data/datakit
    # 嵌入式数据库IntarkDB可开启网络访问功能，相关介绍可以查看README.md
    #url: jdbc:intarkdb:data/datakit?open_remote=true&port=9000&dbname=intarkdb
    druid:
      test-while-idle: true
      test-on-borrow: true
      validation-query: "select 1"
      validation-query-timeout: 10000
      connection-error-retry-attempts: 0
      break-after-acquire-failure: true
      max-wait: 300000
      keep-alive: true
      max-active: 30
      min-evictable-idle-time-millis: 600000
swagger:
  enabled: true
  pathMapping: /dev-api
plugin:
  sortInitPluginIds:
  decrypt:
    enable: false
    className: com.gitee.starblues.common.cipher.AesPluginCipher
    plugins:
      - pluginId: example-basic-1
        props:
          secretKey: mmfvXes1XckCi8F/y9i0uQ==
  version: 0.0.0
plugins:
  oauth-login:
    # A unique identifier obtained by registering with DevKit
    client-id: your_client_id
    # A secret key paired with the client_id
    client-secret: your_client_secret
    datakit-url: https://ip:port
    devkit-url: https://ip:port
    # SSL certificate
    ssl-key: your_ssl_key

