const conditions = [
  '=',
  '!=',
  '<',
  '<=',
  '>',
  '>=',
  'contains',
  'containsCaseInsensitive',
  'doesNotContain',
  'doesNotContainCaseInsensitive',
  'beginsWith',
  'doesNotBeginWith',
  'endsWith',
  'doesNotEndWith',
  'isNull',
  'isNotNull',
  'isEmpty',
  'isNotEmpty',
  'isBetween',
  'isNotBetween',
  'isInList',
  'isNotInList',
];
export default conditions;
